### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by conchoecia** [rrwick/Basecalling-comparison#4]
Great repo! One suggestion that I have is to try to include PacBio RS II and Sequel data for both basecaller accuracy (yes, I know that Sequel reports everything as `!`) and for pre- and post-consensus assembly improvement. This side-by-side comparison would be useful for people who do not know much about Nanopore sequencing and are considering trying it out.

**Comment by rrwick** [comment]
Yes, that would be good, but I'm afraid I don't have PacBio data for this strain, so I can't include it in this comparison. A robust comparison of different sequencing platforms and their resulting reads/assemblies would be awesome, but out of my scope for this repo :smile:

Based on PacBio data I've seen in the past, I'd guess that a Nanopore-vs-PacBio comparison would look something like this:
1) PacBio read accuracy similar to Nanopore, though perhaps with less of a left-tail to the distribution. I.e. PacBio would have fewer reads in the 70s.
2) PacBio consensus accuracy better than Nanopore, probably getting awfully close to 100%
3) After polishing with [Arrow](https://github.com/PacificBiosciences/GenomicConsensus) (a signal-level polisher for PacBio data, sort of like Nanopolish), the PacBio consensus accuracy would get even closer to 100%, leaving only a handful of errors in the whole genome, probably around homopolymers.

As I currently see it, PacBio's higher consensus accuracy is its main (maybe only) advantage over Nanopore at the moment. That's one reason why I'm so interested in Nanopore basecallers and the consensus accuracy they produce, because if and when Nanopore can do as well as PacBio, then I don't think PacBio will have any advantage over Nanopore.

Until that day arrives,  I am a fan of [hybrid Illumina+Nanopore sequencing](http://mgen.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000132). That way you can get completed assemblies with great sequence accuracy.

Ryan
